### ISSUE TITLE
I know this is extremely stupid.

### ISSUE THREAD

**Issue by JitterySkywalker567** [xNVSE/NVSE#147]
But... would there be some way to make a version of nvse that works on consoles?
(I am not asking for you to make it just if there is a way to do it)

**Comment by DarianLStephens** [comment]
I think it's _technically_ possible, but SO much work, and violates so many policies, and possibly laws.

**Comment by VishVadeva50** [comment]
Cant wait to decode the great ps3 version

**Comment by NCRTrooper** [comment]
I'm just commenting here in the hope somebody leaves an emoji when my post shows up in the #github channel on the Discord server.

But why would you want to use xNVSE on console? That would set a dangerous precedence. Imagine all the support requests you'd get to port your mods to consoles. Then again most of them would probably be "How do I use Vortex to install this mod on PS3?" Because God forbid people do things without Vortex.

**Comment by JitterySkywalker567** [comment]
I opened this really late at night I was going down a rabbit hole trying to figure out if TTW was theoretically possible on console so I could get my dad to try it (he refuses to use a pc for games) anyways I closed it when I remembered that it was extremely stupid.

**Comment by Masamune3210** [comment]
Even with custom firmware or any other type of firmware modification that allows for security bypasses, extending the executable privileges of a game to a external scripting engine would be a battle through hell at the very least if not actually impossible within the constraints
