### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by blindhunter892** [xNVSE/NVSE#153]
xNVSE 6.2.8 and 6.2.7 both are coming up with TROJANS from 360 security for PC

**Comment by blindhunter892** [comment]
xNVSE 6.2.6 is clean

**Comment by Masamune3210** [comment]
Next time, please look at other issues. This has been answered many times before, this project has never and will never have malicious code in it. The reason AV solutions detect it as malicious is because of how the mod works. Heuristic detection is easily tripped by design, be it a bad design decision or not. Regardless, NVSE is not malicious

**Comment by blindhunter892** [comment]
Not if it's causing BSODs

**Comment by WallSoGB** [comment]
Virus

**Comment by Masamune3210** [comment]
It's not causing BSOD's, it literally can't lol. User mode code cannot and will never be. It can trigger bugs in higher level components which can cause a issue but it cannot cause one itself

**Comment by NCRTrooper** [comment]
Guys! Guys! Guys! xNVSE is a virus unlike any other! The other day I installed it! Not only did it cause a blue screen, but it also caused all the fans in my computer to shutdown! Then it started getting really hot! The power button wouldn't work! Neither did unplugging it from the wall! Eventually my CPU and GPU caught fire! It burned down the whole neighborhood! The fire is still raging today and it's going to consume the entirety of the east coast of the USA if it isn't stopped! 

This xNVSE thing is nothing to mess around with!

**Comment by Masamune3210** [comment]
Didn't you read the latest release notes? Runaway Thermonuclear Reactions are just how you know it's working!
