### ISSUE TITLE
Been getting several GECK  crashes when clicking Save Script button

### ISSUE THREAD

**Issue by KirkH420** [xNVSE/NVSE#53]
Unfortunately whatever is happening is bad enough that no crash save was generated each time it happened.
I've been using a Lambda function/script and this is the only time I've seen that happen. I mean, I know that I'm still getting the hang of Lambda, but I wouldn't think the geck should drop out like that an not even be able to catch a crash save.
So I thought I'd come here and mention it in case it's relevant to something. 

(i made sure to check for xNVSE updates)

**Comment by korri123** [comment]
Please post the script.

**Comment by KirkH420** [comment]
BEGIN MenuMode 3;	{CONSOLE OPEN]

;Lambda UDF Function
CallForSeconds 0.01 (BEGIN Function {}
				
	if (bConsoleIsOpen == FALSE)
		;MessageBoxEx "About to print time remaining."
		PrintC " "

			Set sTemp 	To "%0.Yf" (fMorphineEffectTimer / 60)
			Set fSec	To #sTemp
			Set sTemp 	To "%1.0f" (fMorphineEffectTimer / 60)
			Set fMin	To #sTemp
			Set fSec	To fSec * (60/1)
			Set sTemp 	To "0" + #fMin + ":" + #fSec

			;if (bDebugModeEnabled == TRUE)
			PrintC "StealthSuitOS: Med-X wears off in %z." $sTemp

			Set bConsoleIsOpen To TRUE
	endif

END)

**Comment by KirkH420** [comment]
i chopped off the final END, so that's supposed to be there too

**Comment by korri123** [comment]
The crash is from GECK extender (unrelated to lambda). I'll look into issuing a fix. The issue stems from these lines that have a syntax error:
`Set sTemp 	To "%0.Yf" (fMorphineEffectTimer / 60)`
This should be
`let fSec := Sv_Construct "%0.Yf" (fMorphineEffectTimer / 60)`
You need to fix it for all the lines.

`Set fSec To #sTemp` needs to be `Let fSec := #sTemp` since # is an NVSE operator and Set To does not support those. It's a good rule of thumb to avoid Set To and use Let := in general with xNVSE.  (List of NVSE operators can be seen here: https://geckwiki.com/index.php?title=NVSE_Expressions). There is also a nice assignment macro that can be used instead of Let (which gets translated to let during compilation): https://geckwiki.com/index.php?title=Let_Macro

**Comment by KirkH420** [comment]
Yes okay that makes sense! Thanks. That's cool that you can figure that out like that.
